
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:seasonal_orchard", "biomesoplenty:highland_moor", "terralith:cloud_forest", "minecraft:forest", "biomesoplenty:bayou", "autumnity:maple_forest", "biomesoplenty:marsh", "biomesoplenty:muskeg", "ars_nouveau:archwood_forest", "biomesoplenty:mystic_grove", "biomesoplenty:redwood_forest", "minecraft:mangrove_swamp", "terralith:ice_marsh", "minecraft:old_growth_birch_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:wetland", "minecraft:grove", "biomesoplenty:orchard", "minecraft:birch_forest", "terralith:orchid_swamp", "terralith:alpine_grove", "minecraft:swamp", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:bamboo_grove", "biomesoplenty:floodplain", "biomesoplenty:woodland", "minecraft:dark_forest", "biomesoplenty:bog", "minecraft:flower_forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 8
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:grove", "biomesoplenty:seasonal_orchard", "biomesoplenty:orchard", "terralith:cloud_forest", "minecraft:forest", "minecraft:birch_forest", "autumnity:maple_forest", "terralith:alpine_grove", "ars_nouveau:archwood_forest", "biomesoplenty:mystic_grove", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:woodland", "minecraft:dark_forest", "minecraft:flower_forest", "minecraft:old_growth_birch_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 12.5

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:seasonal_orchard", "biomesoplenty:highland_moor", "terralith:cloud_forest", "minecraft:forest", "biomesoplenty:bayou", "autumnity:maple_forest", "biomesoplenty:marsh", "biomesoplenty:muskeg", "ars_nouveau:archwood_forest", "biomesoplenty:mystic_grove", "biomesoplenty:redwood_forest", "minecraft:mangrove_swamp", "terralith:ice_marsh", "minecraft:old_growth_birch_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:wetland", "minecraft:grove", "biomesoplenty:orchard", "minecraft:birch_forest", "terralith:orchid_swamp", "terralith:alpine_grove", "minecraft:swamp", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:bamboo_grove", "biomesoplenty:floodplain", "biomesoplenty:woodland", "minecraft:dark_forest", "biomesoplenty:bog", "minecraft:flower_forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:grove", "biomesoplenty:seasonal_orchard", "biomesoplenty:orchard", "terralith:cloud_forest", "minecraft:forest", "minecraft:birch_forest", "autumnity:maple_forest", "terralith:alpine_grove", "ars_nouveau:archwood_forest", "biomesoplenty:mystic_grove", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:woodland", "minecraft:dark_forest", "minecraft:flower_forest", "minecraft:old_growth_birch_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 30
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["terralith:amethyst_canyon", "terralith:yellowstone", "minecraft:snowy_slopes", "biomesoplenty:marsh", "biomesoplenty:dune_beach", "biomesoplenty:maple_woods", "biomesoplenty:highland", "terralith:lush_valley", "biomesoplenty:seasonal_forest", "atmospheric:sparse_rainforest", "terralith:snowy_badlands", "minecraft:grove", "terralith:siberian_taiga", "minecraft:old_growth_pine_taiga", "terralith:orchid_swamp", "terralith:scarlet_mountains", "minecraft:stony_peaks", "biomesoplenty:lush_savanna", "biomesoplenty:lavender_field", "terralith:fractured_savanna", "biomesoplenty:floodplain", "minecraft:windswept_gravelly_hills", "terralith:snowy_maple_forest", "terralith:bryce_canyon", "terralith:tropical_jungle", "biomesoplenty:pumpkin_patch", "biomesoplenty:clover_patch", "biomesoplenty:seasonal_orchard", "terralith:alpine_highlands", "biomesoplenty:fungal_jungle", "minecraft:jungle", "terralith:volcanic_peaks", "minecraft:forest", "biomesoplenty:tropics", "biomesoplenty:bayou", "autumnity:maple_forest", "minecraft:sparse_jungle", "terralith:caldera", "minecraft:frozen_peaks", "terralith:emerald_peaks", "minecraft:windswept_forest", "ars_nouveau:archwood_forest", "biomesoplenty:mystic_grove", "terralith:jungle_mountains", "terralith:white_cliffs", "biomesoplenty:lush_desert", "terralith:shield", "minecraft:old_growth_birch_forest", "biomesoplenty:wetland", "biomesoplenty:volcano", "minecraft:lush_caves", "biomesoplenty:coniferous_forest", "biomesoplenty:bamboo_grove", "minecraft:taiga", "biomesoplenty:jade_cliffs", "biomesoplenty:highland_moor", "biomesoplenty:crag", "minecraft:beach", "terralith:rocky_jungle", "terralith:gravel_desert", "terralith:basalt_cliffs", "terralith:ashen_savanna", "minecraft:snowy_taiga", "biomesoplenty:muskeg", "terralith:amethyst_rainforest", "biomesoplenty:rocky_rainforest", "minecraft:mangrove_swamp", "terralith:ice_marsh", "biomesoplenty:field", "biomesoplenty:forested_field", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:volcanic_plains", "terralith:wintry_forest", "biomesoplenty:orchard", "terralith:rocky_mountains", "minecraft:jagged_peaks", "biomesoplenty:wasteland", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:bog", "terralith:haze_mountain", "terralith:forested_highlands", "biomesoplenty:fir_clearing", "terralith:wintry_lowlands", "atmospheric:sparse_rainforest_basin", "minecraft:windswept_hills", "terralith:cloud_forest", "terralith:rocky_shrubland", "biomesoplenty:rainforest", "biomesoplenty:lavender_forest", "minecraft:bamboo_jungle", "biomesoplenty:redwood_forest", "terralith:cave/underground_jungle", "terralith:gravel_beach", "terralith:siberian_grove", "minecraft:snowy_beach", "terralith:volcanic_crater", "atmospheric:rainforest_basin", "biomesoplenty:snowy_maple_woods", "minecraft:birch_forest", "atmospheric:rainforest", "terralith:alpine_grove", "minecraft:swamp", "biomesoplenty:snowy_fir_clearing", "biomesoplenty:woodland", "minecraft:dark_forest", "minecraft:meadow", "biomesoplenty:ominous_woods", "minecraft:flower_forest", "minecraft:snowy_plains", "biomesoplenty:mediterranean_forest", "biomesoplenty:wooded_wasteland"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

