
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 861775
	#The name of the modpack
	modpackName = "Finality"
	#The version of the modpack
	modpackVersion = "0.3.8b"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

